package com.codename1.demos.nativecontrolsdemo;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.nui.NSelect;
import static com.codename1.ui.ComponentSelector.$;
import com.codename1.ui.Font;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class NativeControlsDemo {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);
        NSelect.setUseLightWeightWidget(true);
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        
        hi.add(new Label("Hi World"));
        Label result = new Label();
        NSelect<String> select = new NSelect<>();
        $(select).selectAllStyles()
                .setFont(Font.createTrueTypeFont(Font.NATIVE_MAIN_LIGHT, 4f))
                .setFgColor(0xff0000)
                .setBgColor(0x00ff00)
                ;
        select.setOptions("Red", "Green", "Blue", "Orange");
        select.addSelectionListener((i1, i2)->{
            result.setText(select.getOption(select.getSelectedIndex()));
            hi.revalidateWithAnimationSafety();
        });
        hi.add(result);
        hi.add(select);
        
        
        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
